package DBD::Unify::TypeInfo;

# The %type_info_all hash was automatically generated by
# DBI::DBD::Metadata::write_typeinfo_pm v2.008696.
# And manually reformatted into readable style

use strict;
use warnings;

require Exporter;
require DynaLoader;

use vars  qw(@ISA @EXPORT $type_info_all);
@ISA    = qw(Exporter DynaLoader);
@EXPORT = qw($type_info_all);
use DBI   qw(:sql_types);

$type_info_all = [
    {	TYPE_NAME          =>  0,
	DATA_TYPE          =>  1,
	COLUMN_SIZE        =>  2,
	LITERAL_PREFIX     =>  3,
	LITERAL_SUFFIX     =>  4,
	CREATE_PARAMS      =>  5,
	NULLABLE           =>  6,
	CASE_SENSITIVE     =>  7,
	SEARCHABLE         =>  8,
	UNSIGNED_ATTRIBUTE =>  9,
	FIXED_PREC_SCALE   => 10,
	AUTO_UNIQUE_VALUE  => 11,
	LOCAL_TYPE_NAME    => 12,
	MINIMUM_SCALE      => 13,
	MAXIMUM_SCALE      => 14,
	SQL_DATA_TYPE      => 15,
	SQL_DATETIME_SUB   => 16,
	NUM_PREC_RADIX     => 17,
	INTERVAL_PRECISION => 18,
	},
    [ "BINARY",          SQL_LONGVARBINARY,undef,"'",  "'",  undef,            1,0,0,undef,undef,undef,undef,undef,undef,undef,undef,undef,undef, ],
    [ "BYTE",            SQL_VARBINARY,    undef,"'",  "'",  "MAX LENGTH",     1,0,3,undef,undef,undef,undef,undef,undef,undef,undef,undef,undef, ],
    [ "TEXT",            SQL_LONGVARCHAR,  undef,"'",  "'",  undef,            1,0,0,undef,undef,undef,undef,undef,undef,undef,undef,undef,undef, ],
    [ "CHAR",            SQL_VARCHAR,      undef,"'",  "'",  "MAX LENGTH",     1,1,3,undef,undef,undef,undef,undef,undef,undef,undef,undef,undef, ],
    [ "INT",             SQL_INTEGER,      undef,undef,undef,undef,            1,0,3,0,    undef,undef,undef,0,    0,    undef,undef,undef,undef, ],
    [ "SMALLINT",        SQL_SMALLINT,     undef,undef,undef,undef,            1,0,3,0,    undef,undef,undef,0,    0,    undef,undef,undef,undef, ],
    [ "DOUBLE PRECISION",SQL_DOUBLE,       undef,undef,undef,undef,            1,0,3,0,    undef,undef,undef,0,    undef,undef,undef,undef,undef, ],
    [ "FLOAT",           SQL_FLOAT,        undef,undef,undef,undef,            1,0,3,0,    undef,undef,undef,0,    undef,undef,undef,undef,undef, ],
    [ "REAL",            SQL_REAL,         undef,undef,undef,undef,            1,0,3,0,    undef,undef,undef,0,    undef,undef,undef,undef,undef, ],
    [ "TIME",            SQL_TIME,         undef,undef,undef,undef,            1,0,3,undef,undef,undef,undef,undef,undef,undef,undef,undef,undef, ],
    [ "HUGE DATE",       SQL_DATE,         undef,undef,undef,undef,            1,0,3,undef,undef,undef,undef,undef,undef,undef,undef,undef,undef, ],
    [ "DATE",            SQL_DATE,         undef,undef,undef,undef,            1,0,3,undef,undef,undef,undef,undef,undef,undef,undef,undef,undef, ],
    [ "HUGE AMOUNT",     SQL_NUMERIC,      undef,undef,undef,"PRECISION",      1,0,3,0,    undef,undef,undef,2,    2,    undef,undef,undef,undef, ],
    [ "AMOUNT",          SQL_NUMERIC,      undef,undef,undef,"PRECISION",      1,0,3,0,    undef,undef,undef,2,    2,    undef,undef,undef,undef, ],
    [ "CURRENCY",        SQL_DECIMAL,      undef,undef,undef,"PRECISION,SCALE",1,0,3,0,    undef,undef,undef,0,    8,    undef,undef,undef,undef, ],
    [ "HUGE INT",        SQL_DECIMAL,      undef,undef,undef,undef,            1,0,3,0,    undef,undef,undef,0,    0,    undef,undef,undef,undef, ],
    ];

1;
